# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "outpost-barbican"
SPDX-PackageSupplier = "Ledger SAS <outpost-os@ledger.fr>"
SPDX-PackageDownloadLocation = "https://github.com/outpost-os/barbican"

[[annotations]]
path = "doc/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Ledger SAS"
SPDX-License-Identifier = "Apache-2.0"
