; SPDX-FileCopyrightText: 2024 Ledger SAS
;
; SPDX-License-Identifier: Apache-2.0

[tox]
min_version = 4.0
env_list =
  lint
  unittests
  docs
isolated_build = true

[tox:.package]
basepython = python3

[testenv]
extras = devel

[testenv:unittests]
commands =
  pytest --basetemp={envtmpdir} --cov=camelot.barbican --tb=long -vv {posargs}
  coverage report -m
  coverage xml

[testenv:lint]
extras = devel,doc
commands =
  black --line-length 100 --check --diff . doc/_ext
  mypy -p camelot.barbican
  mypy doc/_ext
  flake8  --docstring-convention=numpy
  flake8  --docstring-convention=numpy doc/_ext

[testenv:docs]
extras = doc
commands =
  sphinx-build -b html doc/ .doc/_html
  sphinx-build -b simplepdf  doc/ .doc/_pdf

[flake8]
select = C, D, E, F, W, B, B9, DOC

# XXX:
# Some flake8 rules conflicts with Black and/or aren't PEP8 compliant, in case of conflit we
# choose the Black way of doing.
#  - D1xx: missing docstring family (all docstring must be valid but missing is not fatal error)
#  - E203: is not PEP8 compliant and conflict with blake, must be disabled
#  - E704: complain about collapse impl. for elided func/method/class which is allowed by PEP8
#          Black will ensure that this is the only case in which one should write a oneliner.
#  - W503: W503 and W504 and non compatible rules enabled by default by flake8 (...), one again
#          Black is the reference and thus W503 is disabled.
#  - DOC601/603: autoapi generate multiple description for class and/or instance attributes if they
#                are documented in class' docstring. As autoapi maintainers won't fix this issue
#                (ignoring the fact that a valid docstring leads to invalid rst files), we have to
#                document attributes in a non standard way and ignore this warning until fix by
#                autoapi (very unlikely) or a workaround in autoapi templates that we used (more
#                likely, those templates already works around autoapi multiple anchor and label name
#                w/ singlehtml/simplepdf builder).
ignore = D1, E203, E704, W503, DOC601, DOC603
max-line-length = 100
exclude = .git, .github, __pycache__, build, dist, .eggs, .tox, venv, venv*, .venv, .venv*, reports, .mypy_cache
# pydoclint (flake8) plugin opt --style
style = numpy
statistics = True
allow-init-docstring = True

[pytest]
tmp_path_retention_policy = none
